image: gitpod/workspace-full:2024-02-19-11-51-41
vscode:
  extensions:
    - "dbaeumer.vscode-eslint"
    - "ms-azuretools.vscode-docker"

tasks:
  - name: install dependencies and setup process
    command: |
      cp .env.example .env
      echo "API_URL=$(gp url 8080)" >> .env
      docker-compose --profile dev build
      docker-compose --profile dev up -d
